### PR TITLE
Use `Makie.jl` for plotting instead of `Plots.jl`

### PR DESCRIPTION
**Pull request by jbisits**
This PR changes the plotting and animations from `Plots.jl` to `Makie.jl`. I noticed that this transition has occurred in `FourierFlows.jl` and looks to be happening to `GeophysicalFlows.jl` as well (FourierFlows/GeophysicalFlows.jl#288).

### CODE REVIEW

**Comment by jbisits** [comment]
@navidcy I ran into an issue when trying to animate the `celluarflow.jl` example with `Makie.jl`. Do you know if `Makie.jl` can create an animation  using an `Observable` while the `Problem` is being stepped forward? It is nice showing that you can create plots without saving data though so I can look into how to do this or we could leave it with `Plots.jl` for variation? Otherwise I thought it might be most simple to change the example so output is saved and we plot from that (as is the case in the other two examples).

**Comment by navidcy** [comment]
Let me try to see if we can make online animations with Makie. If not, we can leave that example with Plots.

**Comment by navidcy** [comment]
Note the `alpha` is not a Makie kwarg. To change alpha to e.g., 0.8 you do `color = (:grey, 0.8)`.

**Comment by jbisits** [comment]
> Note that as far as I know `alpha` is not a Makie kwarg. To change alpha to e.g., 0.8 you do `color = (:grey, 0.8)`.

I thought that `alpha` could be used in [`contour`](https://makie.juliaplots.org/stable/examples/plotting_functions/contour/). Either way I think that `color = (:grey, 0.8)` is clearer!

**Comment by navidcy** [comment]
> > Note that as far as I know `alpha` is not a Makie kwarg. To change alpha to e.g., 0.8 you do `color = (:grey, 0.8)`.
> 
> I thought that `alpha` could be used in [`contour`](https://makie.juliaplots.org/stable/examples/plotting_functions/contour/). Either way I think that `color = (:grey, 0.8)` is clearer!

You might be right!

**Review by navidcy — APPROVED** [review]
@jbisits can you try running the docs locally to make sure all renders ok? If so merge!

**Comment by jbisits** [comment]
> @jbisits can you try running the docs locally to make sure all renders ok? If so merge!

Sorry I was a little slow @navidcy, you beat me to it!! Thanks very much!

**Pull request merged**
