### PR TITLE
Add particle advection example

### PR DESCRIPTION
**Pull request by jbisits**
This PR adds an example where we are advecting particles in a flow. I was thinking about #2 and thought that if we just set diffusivity to be zero we are solving the advection equation so could maybe use that in lieu (or until) of having some kind of module that advects parcels. It is a little rough and ready but interested to see if you think it worthwhile.

### CODE REVIEW

**Comment by navidcy** [comment]
When I run the example I get this...

https://user-images.githubusercontent.com/7112768/188520755-1d37b868-6cf4-4a14-8f33-5eb8a85acc30.mp4

It's probably tricky to work without diffusivity due to numerical instabilities?

**Comment by jbisits** [comment]
> When I run the example I get this...
> 
>  particle-advection.mp4 
> It's probably tricky to work without diffusivity due to numerical instabilities?

Yes I had did not think the one I ran locally was quite that bad, but the lack of diffusivity does cause problems with numerical instabilities. More seeing if you thought worth pursuing but I think best if I remove this example altogether. If I just close this PR does it get archived but not merged?

**Comment by navidcy** [comment]
Yeap, that's what will happen if you close.

**Comment by navidcy** [comment]
It'll stay in your fork unless you delete that branch.

**Comment by jbisits** [comment]
Ok I think I might do that just in case some inspiration strikes.. Thanks for you help and sorry for the bother with this!

**Pull request closed without merging**
